### ISSUE TITLE
Typescript support broken

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/leonardo#143]
## Description

Class function refactor broke typescript support. Issue identified here: 

https://github.com/adobe/leonardo/issues/113#issuecomment-926028897

## Leonardo package and version

alpha.9+

## Environment
 - **Browser(s) and OS(s):**

**Comment by florianbepunkt** [comment]
Is this lib still maintained? Seems not usable in TS for the time being.

**Comment by NateBaldwinDesign** [comment]
Yes it's still maintained. We accept contributions (including proposals) for solutions like this. I personally am not that familiar with Typescript and the best method to support it in Leonardo. Any recommendations, proposals, or PRs on this topic are welcome!
