### ISSUE TITLE
Oklab color space support

### ISSUE THREAD

**Issue by helloatilla** [adobe/leonardo#147]
I recently discovered this article from Björn Ottosson regarding a better color space for perceptionally uniform colors.
https://bottosson.github.io/posts/oklab/

Here is an interactive review of Oklab: https://raphlinus.github.io/color/2021/01/18/oklab-critique.html#update-2021-01-29

Is it possible to include Oklab color space for leonardo? I'm currently in the creation of an accessible and perceptionally uniform coor system and Oklab would help a lot in this regard.

Thanks for the efforts and helping us all with better color tools.

**Comment by probablyup** [comment]
Came across this too, I'll take a stab at it this weekend if I have time.

**Comment by NateBaldwinDesign** [comment]
That would be great @probablyup 😎

**Comment by aaronadamsCA** [comment]
Any chance you'll add Oklab (probably specifically Okhsl) anytime soon?

CIECAM isn't bad, but Okhsl still looks like it would do a better job.

**Comment by probablyup** [comment]
Will try to make time this week

**Comment by probablyup** [comment]
Thanks Nate! Sorry I couldn't get to it

**Comment by NateBaldwinDesign** [comment]
@probablyup no worries!
