### ISSUE TITLE
Module '"@adobe/leonardo-contrast-colors"' has no exported member 'BackgroundColor'.

### ISSUE THREAD

**Issue by pabloromeroelux** [adobe/leonardo#175]
## Description
I'm trying to set up a TypeScript/React project and use `leonardo-contrast-colors` module but I can't import any of the exports.

Apparently this `import { BackgroundColor, Color, Theme } from "@adobe/leonardo-contrast-colors";` points to `index.d.ts` rather than `index.js`.

I wonder if this is a problem with the package or my project configuration. I can't figure it out.

This is my tsconfig.json:

```
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "target": "ES2015",
    "jsx": "react",
    "typeRoots": ["./node_modules/@types"],
    "module": "ESNext",
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
```

## Steps to reproduce
`npm install @adobe/leonardo-contrast-colors@1.0.0-alpha.13`

Then in the code I do the following according to the example in the README.md:

```
import { BackgroundColor, Color, Theme } from "@adobe/leonardo-contrast-colors";

let gray = new BackgroundColor({
  name: "gray",
  colorKeys: ["#cacaca"],
  ratios: [2, 3, 4.5, 8],
});

let blue = new Color({
  name: "blue",
  colorKeys: ["#5CDBFF", "#0000FF"],
  ratios: [3, 4.5],
});

let red = new Color({
  name: "red",
  colorKeys: ["#FF9A81", "#FF0000"],
  ratios: [3, 4.5],
});

let theme = new Theme({
  colors: [gray, blue, red],
  backgroundColor: gray,
  lightness: 97,
});

```
but I get this error:
Module '"@adobe/leonardo-contrast-colors"' has no exported member 'BackgroundColor'.

## Expected behavior
`import { BackgroundColor, Color, Theme } from "@adobe/leonardo-contrast-colors";` should import BackgroundColor, Color, Theme

## Leonardo package and version
Tried using both 1.0.0-alpha.13 and 1.0.0-alpha.16
According to #173 the latest release is broken.

## Environment
Mac OS

**Comment by NateBaldwinDesign** [comment]
@pabloromeroelux this issue I believe relates to #143 as Leonardo currently does not have Typescript support

**Comment by xaddict** [comment]
Just ran into this for nth time with version 17

**Comment by Jeremy-Walton** [comment]
I also ran into this today. Like the above example with stackblitz, I was using vite with no other dependencies
