### ISSUE TITLE
Help accessing color contrast page 

### ISSUE THREAD

**Issue by melaniejaane** [adobe/leonardo#213]
Please help! Leonardo used to be my go to tool because I found it so intuitive, but now I'm really struggling! 
Can anyone please explain how / where can I access the key color contrast page shown in image?
Thank you :) 

<img width="1334" alt="Leonardo_Screenshot" src="https://github.com/adobe/leonardo/assets/105766543/6bb7f4dc-5d29-4fa1-a339-af0253245626">

**Comment by niitamer** [comment]
Are you referring to the following screen?

![image](https://github.com/adobe/leonardo/assets/85269886/252a3f3f-21c4-4d04-97fb-74015731a42a)

**Comment by Eldresh** [comment]
Hi I was wondering about this too and am definitely not referring to the screen mentioned by niitamer. I explicitly am trying to find out how to get to the screen in the first screenshot posted. The one that is the very first image on the readme. That page, explicitly, is what I need and am looking for and I can't find it anywhere on the website.

**Comment by GarthDB** [comment]
<img width="1818" alt="image" src="https://github.com/adobe/leonardo/assets/125516/3de9e6a8-32d1-45b0-8ec7-6074a5911cc4">
The Adaptive Color Theme tool can be found at https://leonardocolor.io/theme.html
