### ISSUE TITLE
I cannot simply follow the guide and run the project

### ISSUE THREAD

**Issue by miguelgargallo** [adobe/leonardo#225]
## Description

Simply following the instructions, the project does not run properly

## Steps to reproduce

Simple follow the guide

## Expected behavior

Serve on screen poping up

## Screenshots

No need

## Leonardo package and version

Same

## Environment
 - **Browser(s) and OS(s):** 
Win 11, 64bits, Bing or Chrome

## Additional context

No need

**Comment by miguelgargallo** [comment]
Fixed here: waiting for approval https://github.com/adobe/leonardo/pull/227

 - Will be closed once merge is approved!

**Comment by VincentGarreau** [comment]
Any news regarding this? :)

**Comment by miguelgargallo** [comment]
Yes, Waiting since 30 sept
https://github.com/adobe/leonardo/pull/227

**Comment by GarthDB** [comment]
This has been fixed with the [latest release](https://github.com/adobe/leonardo/releases/tag/@adobe/leonardo-contrast-colors@1.0.0). If any problems with the latest package persist, let me know.
