### ISSUE TITLE
Cannot re run the project after the first time

### ISSUE THREAD

**Issue by miguelgargallo** [adobe/leonardo#226]
## Description

I want top serve again and I can't due a critical "-p" directory created before.

## Steps to reproduce

Simple dev, or serve

## Expected behavior

See on my screen poping up

## Screenshots

No need

## Leonardo package and version

Same

## Environment
 - **Browser(s) and OS(s):** 
Win 11 Bing, Chrome or Firefox

## Additional context

No need

**Comment by miguelgargallo** [comment]
Fixed here: waiting for approval https://github.com/adobe/leonardo/pull/227

**Comment by miguelgargallo** [comment]
Fixed here: waiting for approval https://github.com/adobe/leonardo/pull/227

 - Will be closed once merge is approved!

**Comment by GarthDB** [comment]
This has been fixed with the [latest release](https://github.com/adobe/leonardo/releases/tag/@adobe/leonardo-contrast-colors@1.0.0). If any problems with the latest package persist, let me know.

**Comment by miguelgargallo** [comment]
No worries, last time, would be nice to accept PRs instead of copy other's work, have a nice day.

**Comment by GarthDB** [comment]
> No worries, last time, would be nice to accept PRs instead of copy other's work, have a nice day.

What work was copied? It was not intentional and I'd like to resolve if you can let me know.
