### ISSUE TITLE
Links don't save information

### ISSUE THREAD

**Issue by the-real-gabriel** [adobe/leonardo#242]
## Description

When copy the share link and return to it. It appears that only the palette name is preserved.

## Steps to reproduce

1. Go to http://leonardocolor.io/
2. Make changes to a palette
3. Copy share link and visit link.

## Expected behavior

All options would be saved

## Environment

macOS on Chrome and Safari

**Comment by samiamdesigns** [comment]
Can confirm this appears to redirect the custom URL as the parent URL. Came to report this as well but I was beat to it. (:

**Comment by juliennicouleaud** [comment]
Same problem here :(

**Comment by architecb33** [comment]
I also experience this, hope it will be fixed soon 😊

**Comment by GarthDB** [comment]
I had to adjust something to fix a security issue, and I think that's what broke this. I'll work on fixing it today.
