### ISSUE TITLE
Binary search should return closest value larger than search value

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/leonardo#60]
## Description

Binary search currently returns closest match for a search item. While in other applications this would be fine, in Leonardo we need it to return the next closest value that is *larger than* the search item. 

Example:
Ratio input for 3:1 (search for 3)
Generated colors have close matches of 2.9 and 3.03
Current binary search would return **2.9**
Considering the search is typically for a contrast **minimum**, we need the search to return **3.03**

## Environment
 - **Browser(s) and OS(s):**

**Comment by bhavika24** [comment]
Hi @NateBaldwinDesign I would like to work on this. Please can you assign it to me.

**Comment by FazeelUsmani** [comment]
Hi @NateBaldwinDesign, Can you please assign this issue to me? I would like to work on it

**Comment by fedeci** [comment]
If I am not wrong this has already been fixed.

**Comment by FazeelUsmani** [comment]
Oops! thank you for the confirmation, @fedeci

**Comment by bhavika24** [comment]
@fedeci It does not work for all the scenarios. Please find below the test cases for which it fails

1. Should return closest match (ascending)
list = [2, 2.9, 3.01, 3.03];
value = 3

2. Should return closest match (descending)
list = [12, 5, 3.3, 3.14, 3.13, 3.12, 3.1, 3.07, 3, 2, 1]
value = 3.09

![image](https://user-images.githubusercontent.com/63905094/95752563-d2356900-0cbd-11eb-90ec-f1c390795ee4.png)

**Comment by fedeci** [comment]
@bhavika24 You are right, I run tests a couple months ago only evaluating ascending order. My fault.

**Comment by NateBaldwinDesign** [comment]
@FazeelUsmani if you are still interested I can assign this to you. See @bhavika24 's example above. This still needs fixed

**Comment by bhavika24** [comment]
@NateBaldwinDesign  I have fixed it and raised a PR https://github.com/adobe/leonardo/pull/104 for the same. Please review it.

**Comment by FazeelUsmani** [comment]
> @FazeelUsmani if you are still interested I can assign this to you. See @bhavika24 's example above. This still needs fixed

Yeah, I'm interested, @NateBaldwinDesign
