### ISSUE TITLE
Cannot paste HEX value into the color picker

### ISSUE THREAD

**Issue by Dartanjan** [adobe/leonardo#82]
## Description
I'm trying to paste a color into the color picker's HEX value, but it doesn't work.
The context menu isn't there, keyboard shortcut doesn't do anything. This means I need to remember and retype the value myself, which is obviously not ideal.

## Steps to reproduce

1. Copy a HEX code from somewhere, like here: #ffffff
2. Go to http://leonardocolor.io/
3. Click on the Key Color
4. Click on the color mode switch 2 times to get to the HEX value
5. Try to paste the value

## Expected behavior
It should paste the HEX value. If I can type the value myself, it should accept input from the clipboard too.

## Screenshots
![image](https://user-images.githubusercontent.com/3121310/88257112-537fef80-ccbd-11ea-9a09-33bedf0b1a8a.png)

## Environment
 - Chrome 84.0.4147.89 (Official Build) (64-bit)
 - Mac OS 10.14.4

## Additional context
On other browsers it's showing a different/native color picker so I'm unable to produce the same results...

Thanks!

**Comment by NateBaldwinDesign** [comment]
Thank you @Dartanjan !

This issue relates to #67. Unfortunately the update to Chrome’s native controls caused this issue.

**Comment by Dartanjan** [comment]
Ah too bad. At least there's an alternative – I use bulk colors input and just add that one color.

Speaking of which, it looks like for the bulk colors I have to use the number sign character # for every code in the list. This isn't a "problem" but since both Figma and Sketch copy just the HEX value when you select a color (without the hash character) then it adds a bit of work. Would be great if it could just decode both variants, with #f8f8f8 and just f8f8f8.

**Comment by NateBaldwinDesign** [comment]
Thank you, that's a great idea. I've added another ticket for that feature.

**Comment by NateBaldwinDesign** [comment]
FYI @Dartanjan the bulk color input has been updated to support hex codes without the # 

Leaving this issue open as it relates more closely towards a custom color picker / color input control.

**Comment by shaoxp** [comment]
It seems the 'color' type input for Chrome still has this PASTE issue. it will clean to empty when PASTE for any inputbox.  i am using 'color' input as following. 
```
<input type="color" .../>
```
not sure we are talking about the same thing, if Yes. can you please share how to change to use 'the bulk color input'? Thanks.
