### ISSUE TITLE
Disambiguate "adaptive themes" and "themes"

### ISSUE THREAD

**Issue by lazd** [adobe/leonardo#85]
## Description

Calling `generateAdaptiveTheme` returns a function that can be called to generate a theme (set of colors) at a given brightness/contrast. This is a bit confusing, as the word "theme" is overridden.

The documentation shows this here: https://github.com/adobe/leonardo/blob/main/packages/contrast-colors/README.md#pass-your-colors-and-desired-ratios-see-additional-options-below

What is an adaptive theme?

What is a theme?

Those words could be disambiguated.

## Why do you need this feature?

Reduce confusion in documentation :D

## Leonardo package and version

n/a

## Additional context

Writing a postcss plugin to invoke leonardo and struggling with documentation and API naming.

**Comment by NateBaldwinDesign** [comment]
Updates with class functions resolve this issue
