### ISSUE TITLE
Typescript : issue with AdaptiveTheme type | ( optional parameter)

### ISSUE THREAD

**Issue by KirdesMF** [adobe/leonardo#98]
## Description

Currently AdaptiveTheme type :

```ts
// index.d.ts
 type AdaptiveTheme = (brightness: number, constrast: number) => AdaptiveTheme | ({ 
    background: string 
  } | {
    name: string,
    values: {
      name: string,
      contrast: number,
      value: string
    }[]
  })[];
```

```ts
// index.d.ts
  function generateAdaptiveTheme({ 
    colorScales, 
    baseScale,
    brightness,
    contrast, 
    output
  }: {
    colorScales: NamedColorScale[],
    baseScale: string,
    brightness?: number,
    contrast?: number,
    output?: Colorspace,
  }): AdaptiveTheme | never;

```

Ts will complain that an argument is missing if we use the return function of `generateAdaptiveTheme`

## Steps to reproduce

call the return function of `generateAdaptiveTheme` with one argument

```ts
const myTheme = generateAdaptiveTheme({
      colorScales: [primaryScale, secondaryScale, greyScale],
      baseScale: 'primary',
      output: 'HEX',
   }) ;

myTheme(50) // TS waits for `contrast`
```

## Screenshots

![image](https://user-images.githubusercontent.com/54989552/92547274-d3095400-f254-11ea-8285-edbe3b32ce20.png)
![image](https://user-images.githubusercontent.com/54989552/92547330-efa58c00-f254-11ea-96c5-37827bdf7f77.png)
![image](https://user-images.githubusercontent.com/54989552/92548280-e4ebf680-f256-11ea-8506-80eefc3f0b7c.png)

## Leonardo package and version

@leonardo-contrast-colors version: 1.0.0-alpha.8

## Additional context

Set `contrast` as optional

```ts
  type AdaptiveTheme = (brightness: number, constrast?: number) => AdaptiveTheme | ({ 
    background: string 
  } | {
    name: string,
    values: {
      name: string,
      contrast: number,
      value: string
    }[]
  })[];
```

**Comment by NateBaldwinDesign** [comment]
👍 thank you for this fix!
